config/routes.rb
Rails.application.routes.draw do
  resources :comic_chapters
  resources :comics
  resources :magazine_volumes
  get 'votes/new'
  get 'magazine/:magazine_id/votes/new', controller: :votes, action: :new

  resources :magazines

end

app/models/comic_chapter.rb
class ComicChapter < ActiveRecord::Base
	belongs_to :comic
	belongs_to :magazine_volume
end

app/controllers/comic_chapters_controller.rb
class ComicChaptersController < ApplicationController
  before_action :set_comic_chapter, only: [:show, :edit, :update, :destroy]

  # GET /comic_chapters
  # GET /comic_chapters.json
  def index
    @comic_chapters = ComicChapter.all
  end

  # GET /comic_chapters/1
  # GET /comic_chapters/1.json
  def show
  end

  # GET /comic_chapters/new
  def new
    @comic_chapter = ComicChapter.new
  end

  # GET /comic_chapters/1/edit
  def edit
  end

  # POST /comic_chapters
  # POST /comic_chapters.json
  def create
    @comic_chapter = ComicChapter.new(comic_chapter_params)

    respond_to do |format|
      if @comic_chapter.save
        format.html { redirect_to @comic_chapter, notice: 'Comic chapter was successfully created.' }
        format.json { render :show, status: :created, location: @comic_chapter }
      else
        format.html { render :new }
        format.json { render json: @comic_chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comic_chapters/1
  # PATCH/PUT /comic_chapters/1.json
  def update
    respond_to do |format|
      if @comic_chapter.update(comic_chapter_params)
        format.html { redirect_to @comic_chapter, notice: 'Comic chapter was successfully updated.' }
        format.json { render :show, status: :ok, location: @comic_chapter }
      else
        format.html { render :edit }
        format.json { render json: @comic_chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comic_chapters/1
  # DELETE /comic_chapters/1.json
  def destroy
    @comic_chapter.destroy
    respond_to do |format|
      format.html { redirect_to comic_chapters_url, notice: 'Comic chapter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comic_chapter
      @comic_chapter = ComicChapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comic_chapter_params
      params.require(:comic_chapter).permit(:number, :subtitle, :total_point, :comic_id)
    end
end

app/helpers/comic_chapters_helper.rb
module ComicChaptersHelper
end

app/views/comic_chapters/_form.html.erb
<%= form_for(@comic_chapter) do |f| %>
  <% if @comic_chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comic_chapter.errors.count, "error") %> prohibited this comic_chapter from being saved:</h2>

      <ul>
      <% @comic_chapter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
  <div class="field">
    <%= f.label :comic_id %><br>
    <%= f.collection_select(:comic_id, Comic.all, :id, :title, prompt: true) %>
  </div>


  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br>
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :total_point %><br>
    <%= f.number_field :total_point %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comic_chapters/edit.html.erb
<h1>Editing Comic Chapter</h1>

<%= render 'form' %>

<%= link_to 'Show', @comic_chapter %> |
<%= link_to 'Back', comic_chapters_path %>

app/views/comic_chapters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comic Chapters</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Number</th>
      <th>Subtitle</th>
      <th>Total point</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comic_chapters.each do |comic_chapter| %>
      <tr>
        <td><%= Comic.find(comic_chapter.comic_id).title %></td>
        <td><%= comic_chapter.number %></td>
        <td><%= comic_chapter.subtitle %></td>
        <td><%= comic_chapter.total_point %></td>
        <td><%= link_to 'Show', comic_chapter %></td>
        <td><%= link_to 'Edit', edit_comic_chapter_path(comic_chapter) %></td>
        <td><%= link_to 'Destroy', comic_chapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comic chapter', new_comic_chapter_path %>

app/views/comic_chapters/new.html.erb
<h1>New Comic Chapter</h1>

<%= render 'form' %>

<%= link_to 'Back', comic_chapters_path %>

app/views/comic_chapters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= link_to Comic.find(@comic_chapter.comic_id).title, comic_path(@comic_chapter.comic_id) %>
</p>

<p>
  <strong>Number:</strong>
  <%= @comic_chapter.number %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @comic_chapter.subtitle %>
</p>

<p>
  <strong>Total point:</strong>
  <%= @comic_chapter.total_point %>
</p>

<%= link_to 'Edit', edit_comic_chapter_path(@comic_chapter) %> |
<%= link_to 'Back', comic_chapters_path %>