config/routes.rb
Rails.application.routes.draw do
  resources :comic_chapters
  resources :comics
  resources :magazine_volumes
  get 'votes/new'
  get 'magazine/:magazine_id/votes/new', controller: :votes, action: :new

  resources :magazines

end

app/models/comic.rb
class Comic < ActiveRecord::Base
	has_many :comic_chapters
	has_many :carriages
	has_many :magazines, through: :carriages

	accepts_nested_attributes_for :carriages
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  before_action :set_comic, only: [:show, :edit, :update, :destroy]

  # GET /comics
  # GET /comics.json
  def index
    @comics = Comic.all
  end

  # GET /comics/1
  # GET /comics/1.json
  def show
    @comic_chapters = @comic.comic_chapters
  end

  # GET /comics/new
  def new
    @comic = Comic.new
    @comic.carriages.build
  end

  # GET /comics/1/edit
  def edit
  end

  # POST /comics
  # POST /comics.json
  def create
    @comic = Comic.new(comic_params)

    respond_to do |format|
      if @comic.save
        format.html { redirect_to @comic, notice: 'Comic was successfully created.' }
        format.json { render :show, status: :created, location: @comic }
      else
        format.html { render :new }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comics/1
  # PATCH/PUT /comics/1.json
  def update
    respond_to do |format|
      if @comic.update(comic_params)
        format.html { redirect_to @comic, notice: 'Comic was successfully updated.' }
        format.json { render :show, status: :ok, location: @comic }
      else
        format.html { render :edit }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comics/1
  # DELETE /comics/1.json
  def destroy
    @comic.destroy
    respond_to do |format|
      format.html { redirect_to comics_url, notice: 'Comic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comic
      @comic = Comic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comic_params
      params.require(:comic).permit(:title, :author, :score, carriages_attributes: [:id, :magazine_id])
    end
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/views/comics/_form.html.erb
<%= form_for(@comic) do |f| %>
  <% if @comic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comic.errors.count, "error") %> prohibited this comic from being saved:</h2>

      <ul>
      <% @comic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= label_tag :magazine_id %><br>
    <%= f.fields_for(:carriages) do |cf| %>
      <%= cf.collection_select(:magazine_id, Magazine.all, :id, :name, prompt: true) %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comics/edit.html.erb
<h1>Editing Comic</h1>

<%= render 'form' %>

<%= link_to 'Show', @comic %> |
<%= link_to 'Back', comics_path %>

app/views/comics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comics</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comics.each do |comic| %>
      <tr>
        <td><%= comic.title %></td>
        <td><%= comic.author %></td>
        <td><%= comic.score %></td>
        <td><%= link_to 'Show', comic %></td>
        <td><%= link_to 'Edit', edit_comic_path(comic) %></td>
        <td><%= link_to 'Destroy', comic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comic', new_comic_path %>

app/views/comics/new.html.erb
<h1>New Comic</h1>

<%= render 'form' %>

<%= link_to 'Back', comics_path %>

app/views/comics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @comic.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @comic.author %>
</p>

<p>
  <strong>Score:</strong>
  <%= @comic.score %>
</p>

<p>
  <strong>Chapters</strong>
  <table>
  <% @comic_chapters.each do |comic_chapter| %>
    <tr>
      <td><%= comic_chapter.subtitle %></td>
      <td><%= comic_chapter.number %></td>
    </tr>
  <% end %>
  </table>
</p>

<%= link_to 'Edit', edit_comic_path(@comic) %> |
<%= link_to 'Back', comics_path %>