config/routes.rb
Rails.application.routes.draw do
  resources :comic_chapters
  resources :comics
  resources :magazine_volumes
  get 'votes/new'
  get 'magazine/:magazine_id/votes/new', controller: :votes, action: :new

  resources :magazines

end

app/models/magazine.rb
class Magazine < ActiveRecord::Base
	has_many :magazine_volumes
	has_many :carriages
	has_many :comics, through: :carriages
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  before_action :set_magazine, only: [:show, :edit, :update, :destroy]

  # GET /magazines
  # GET /magazines.json
  def index
    @magazines = Magazine.all
  end

  # GET /magazines/1
  # GET /magazines/1.json
  def show
    @magazine_volumes = MagazineVolume.where({magazine_id: @magazine.id})
  end

  # GET /magazines/new
  def new
    @magazine = Magazine.new
  end

  # GET /magazines/1/edit
  def edit
  end

  # POST /magazines
  # POST /magazines.json
  def create
    @magazine = Magazine.new(magazine_params)

    respond_to do |format|
      if @magazine.save
        format.html { redirect_to @magazine, notice: 'Magazine was successfully created.' }
        format.json { render :show, status: :created, location: @magazine }
      else
        format.html { render :new }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /magazines/1
  # PATCH/PUT /magazines/1.json
  def update
    respond_to do |format|
      if @magazine.update(magazine_params)
        format.html { redirect_to @magazine, notice: 'Magazine was successfully updated.' }
        format.json { render :show, status: :ok, location: @magazine }
      else
        format.html { render :edit }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magazines/1
  # DELETE /magazines/1.json
  def destroy
    @magazine.destroy
    respond_to do |format|
      format.html { redirect_to magazines_url, notice: 'Magazine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_magazine
      @magazine = Magazine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def magazine_params
      params.require(:magazine).permit(:name)
    end
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/views/magazines/_form.html.erb
<%= form_for(@magazine) do |f| %>
  <% if @magazine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@magazine.errors.count, "error") %> prohibited this magazine from being saved:</h2>

      <ul>
      <% @magazine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/magazines/edit.html.erb
<h1>Editing Magazine</h1>

<%= render 'form' %>

<%= link_to 'Show', @magazine %> |
<%= link_to 'Back', magazines_path %>

app/views/magazines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Magazines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @magazines.each do |magazine| %>
      <tr>
        <td><%= magazine.name %></td>
        <td><%= link_to 'Show', magazine %></td>
        <td><%= link_to 'Edit', edit_magazine_path(magazine) %></td>
        <td><%= link_to 'Destroy', magazine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Magazine', new_magazine_path %>

app/views/magazines/new.html.erb
<h1>New Magazine</h1>

<%= render 'form' %>

<%= link_to 'Back', magazines_path %>

app/views/magazines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @magazine.name %>
</p>

<%= link_to 'Edit', edit_magazine_path(@magazine) %> |
<%= link_to 'Back', magazines_path %>

<table>
  <thead>
    <tr>
      <th>Magazine</th>
      <th>Number</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @magazine_volumes.each do |magazine_volume| %>
      <tr>
        <td><%= Magazine.find(magazine_volume.magazine_id).name %></td>
        <td><%= magazine_volume.number %></td>
        <td><%= magazine_volume.published %></td>
        <td><%= link_to 'Show', magazine_volume %></td>
        <td><%= link_to 'Edit', edit_magazine_volume_path(magazine_volume) %></td>
        <td><%= link_to 'Destroy', magazine_volume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>