config/routes.rb
Rails.application.routes.draw do
  resources :comic_chapters
  resources :comics
  resources :magazine_volumes
  get 'votes/new'
  get 'magazine/:magazine_id/votes/new', controller: :votes, action: :new

  resources :magazines

end

app/models/magazine_volume.rb
class MagazineVolume < ActiveRecord::Base
	validates :magazine_id, presence: true
	belongs_to :magazine
	has_many :comic_chapters
end

app/controllers/magazine_volumes_controller.rb
class MagazineVolumesController < ApplicationController
  before_action :set_magazine_volume, only: [:show, :edit, :update, :destroy]

  # GET /magazine_volumes
  # GET /magazine_volumes.json
  def index
    @magazine_volumes = MagazineVolume.all
   
  end

  # GET /magazine_volumes/1
  # GET /magazine_volumes/1.json
  def show
    @comic_chapters = ComicChapter.where(magazine_volume_id: @magazine_volume.id)
  end

  # GET /magazine_volumes/new
  def new
    @magazine_volume = MagazineVolume.new
  end

  # GET /magazine_volumes/1/edit
  def edit
  end

  # POST /magazine_volumes
  # POST /magazine_volumes.json
  def create
    @magazine_volume = MagazineVolume.new(magazine_volume_params)

    respond_to do |format|
      if @magazine_volume.save
        format.html { redirect_to @magazine_volume, notice: 'Magazine volume was successfully created.' }
        format.json { render :show, status: :created, location: @magazine_volume }
      else
        format.html { render :new }
        format.json { render json: @magazine_volume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /magazine_volumes/1
  # PATCH/PUT /magazine_volumes/1.json
  def update
    respond_to do |format|
      if @magazine_volume.update(magazine_volume_params)
        format.html { redirect_to @magazine_volume, notice: 'Magazine volume was successfully updated.' }
        format.json { render :show, status: :ok, location: @magazine_volume }
      else
        format.html { render :edit }
        format.json { render json: @magazine_volume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magazine_volumes/1
  # DELETE /magazine_volumes/1.json
  def destroy
    @magazine_volume.destroy
    respond_to do |format|
      format.html { redirect_to magazine_volumes_url, notice: 'Magazine volume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_magazine_volume
      @magazine_volume = MagazineVolume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def magazine_volume_params
      params.require(:magazine_volume).permit(:magazine_id, :number, :published)
    end
end

app/helpers/magazine_volumes_helper.rb
module MagazineVolumesHelper
end

app/views/magazine_volumes/_form.html.erb
<%= form_for(@magazine_volume) do |f| %>
  <% if @magazine_volume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@magazine_volume.errors.count, "error") %> prohibited this magazine_volume from being saved:</h2>

      <ul>
      <% @magazine_volume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
    <div class="field">
      <%= f.label :magazine_id %><br>
      <%= f.collection_select(:magazine_id, Magazine.all, :id, :name, prompt: true) %>
    </div>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.date_select :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/magazine_volumes/edit.html.erb
<h1>Editing Magazine Volume</h1>

<%= render 'form' %>

<%= link_to 'Show', @magazine_volume %> |
<%= link_to 'Back', magazine_volumes_path %>

app/views/magazine_volumes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Magazine Volumes</h1>

<table>
  <thead>
    <tr>
      <th>Magazine</th>
      <th>Number</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @magazine_volumes.each do |magazine_volume| %>
      <tr>
        <td><%= Magazine.find(magazine_volume.magazine_id).name %></td>
        <td><%= magazine_volume.number %></td>
        <td><%= magazine_volume.published %></td>
        <td><%= link_to 'Show', magazine_volume %></td>
        <td><%= link_to 'Edit', edit_magazine_volume_path(magazine_volume) %></td>
        <td><%= link_to 'Destroy', magazine_volume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Magazine volume', new_magazine_volume_path %>

app/views/magazine_volumes/new.html.erb
<h1>New Magazine Volume</h1>

<%= render 'form' %>

<%= link_to 'Back', magazine_volumes_path %>

app/views/magazine_volumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Magazine:</strong>
  <%= Magazine.all.find_by(id: @magazine_volume.magazine_id).name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @magazine_volume.number %>
</p>

<p>
  <strong>Published:</strong>
  <%= @magazine_volume.published %>
</p>

<%= link_to 'Edit', edit_magazine_volume_path(@magazine_volume) %> |
<%= link_to 'Back', magazine_volumes_path %>